import Head from 'next/head'

export default function Home({ children }) {
  return (
    <div>
      <Head>
        <title>100 days css challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          100 days CSS challenge
        </h1>
        {children}
      </main>
    </div>
  )
}
