import Head from 'next/head'

import { node } from 'prop-types'

const propTypes = {
  children: node.isRequired,
}

const Home = ({ children }) => {
  return (
    <div>
      <Head>
        <title>100 days css challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>100 days CSS challenge</h1>
        {children}
      </main>
    </div>
  )
}

Home.propTypes = propTypes

export default Home
